using System.Collections.Generic;
using System.Globalization;

namespace Desktop_Frames
{
    internal static class LocalizationManager
    {
        private static readonly Dictionary<string, string> Korean = new Dictionary<string, string>
        {
            ["About..."] = "정보...",
            ["Options..."] = "옵션...",
            ["Profiles"] = "프로필",
            ["Enable Profile Automation"] = "프로필 자동 전환 사용",
            ["Enable Smart Desktop Auto-Organize"] = "스마트 데스크톱 자동 정리 사용",
            ["Reload All Frames"] = "모든 프레임 다시 불러오기",
            ["Show Hidden Frames"] = "숨겨진 프레임 보이기",
            ["Focus Frame... ({0})"] = "프레임 포커스... ({0})",
            ["Create New Profile..."] = "새 프로필 만들기...",
            ["Enter name for new profile:"] = "새 프로필 이름을 입력하세요:",
            ["New Profile"] = "새 프로필",
            ["Profile '{0}' created successfully."] = "프로필 '{0}'이 생성되었습니다.",
            ["Failed to create profile. Name invalid or already exists."] = "프로필을 만들 수 없습니다. 이름이 잘못되었거나 이미 존재합니다.",
            ["Manage Profiles..."] = "프로필 관리...",
            ["Registry values exported successfully to program folder."] = "레지스트리 값이 프로그램 폴더로 내보내졌습니다.",
            ["Desktop Frames Plus - Error"] = "Desktop Frames Plus - 오류",
            ["Failed to export registry values. Check log for details."] = "레지스트리 값을 내보내지 못했습니다. 자세한 내용은 로그를 확인하세요.",
            ["Reloading all frames, please wait..."] = "모든 프레임을 다시 불러오는 중입니다. 잠시 기다려 주세요...",
            ["An error occurred while reloading frames: {0}"] = "프레임을 다시 불러오는 중 오류가 발생했습니다: {0}",
            ["Create new..."] = "새로 만들기...",
            ["New Frame"] = "새 프레임",
            ["New Portal Frame"] = "새 포털 프레임",
            ["New Note Frame"] = "새 노트 프레임",
            ["Hide all Frames"] = "모든 프레임 숨기기",
            ["Show all Frames"] = "모든 프레임 보이기",
            ["Focus Frame..."] = "프레임 포커스...",
            ["Exit"] = "종료",
            ["Default"] = "기본",
            ["Not Set"] = "설정 안 됨",

            ["Desktop Frames + Options"] = "Desktop Frames + 옵션",
            ["Options"] = "옵션",
            ["General"] = "일반",
            ["Style & FX"] = "스타일 및 효과",
            ["Tools"] = "도구",
            ["Hotkeys"] = "단축키",
            ["Smart Desktop"] = "스마트 데스크톱",
            ["Look Deeper"] = "자세히 보기",
            ["Startup"] = "시작",
            ["Language:"] = "언어:",
            ["Selections"] = "선택",
            ["Start with Windows"] = "Windows 시작 시 실행",
            ["Single Click to Launch"] = "한 번 클릭으로 실행",
            ["Enable Snap Near Frames"] = "프레임 근처 스냅 사용",
            ["Enable Dimension Snap"] = "크기 스냅 사용",
            ["Enable Tray Icon"] = "트레이 아이콘 사용",
            ["Use Recycle Bin on Portal Frames 'Delete item' command"] = "포털 프레임의 '항목 삭제'에서 휴지통 사용",
            ["Show 'New Frame' in Desktop Context Menu"] = "데스크톱 컨텍스트 메뉴에 '새 프레임' 표시",
            ["Enable Portal Frames Watermark"] = "포털 프레임 워터마크 사용",
            ["Enable Note Frames Watermark (Coming Soon)"] = "노트 프레임 워터마크 사용(준비 중)",
            ["Disable Frame Scrollbars"] = "프레임 스크롤바 비활성화",
            ["Enable Sounds"] = "소리 사용",
            ["Notification Sound:"] = "알림 소리:",
            ["Default Sound"] = "기본 소리",
            ["Double Ding"] = "더블 딩",
            ["Smooth Tickle"] = "부드러운 알림",
            ["Message Ding"] = "메시지 딩",
            ["Gentle Ding"] = "잔잔한 딩",
            ["Soft Ding"] = "소프트 딩",

            ["Appearance"] = "모양",
            ["Enable Chameleon Mode (Auto-match Wallpaper Color)"] = "카멜레온 모드 사용(배경화면 색상 자동 맞춤)",
            ["Frames will automatically change color to blend perfectly with your desktop background."] = "프레임 색상이 데스크톱 배경에 맞게 자동으로 변경됩니다.",
            ["Frame Tint"] = "프레임 색조",
            ["Menu Tint"] = "메뉴 색조",
            ["Auto-Hide Frames"] = "프레임 자동 숨김",
            ["Auto hide frames"] = "프레임 자동 숨김",
            ["Auto hide time (sec)"] = "자동 숨김 시간(초)",
            ["Idle Fade-Out"] = "유휴 시 페이드아웃",
            ["Enable Idle Fade-Out"] = "유휴 페이드아웃 사용",
            ["Idle Time (sec)"] = "유휴 시간(초)",
            ["Fade Target Opacity (%)"] = "페이드 목표 투명도(%)",
            ["Idle Auto-Roll"] = "유휴 자동 말기",
            ["Desktop Icon Visibility"] = "데스크톱 아이콘 표시",
            ["Hide native desktop icons while program is running"] = "프로그램 실행 중 기본 데스크톱 아이콘 숨기기",
            ["Hide native desktop icons when Frames are hidden"] = "프레임이 숨겨졌을 때 기본 데스크톱 아이콘 숨기기",
            ["Icons"] = "아이콘",
            ["Menu Icon"] = "메뉴 아이콘",
            ["Lock Icon"] = "잠금 아이콘",
            ["Color"] = "색상",
            ["Effect"] = "효과",

            ["Backup"] = "백업",
            ["Restore..."] = "복원...",
            ["Open Backups Folder"] = "백업 폴더 열기",
            ["Automatic Backup (Daily)"] = "자동 백업(매일)",
            ["Maintenance"] = "유지 관리",
            ["Screen Bound Frames"] = "프레임을 화면 안으로 이동",
            ["All frames have been checked and moved within valid screen bounds."] = "모든 프레임을 확인하고 화면 안쪽으로 이동했습니다.",
            ["Success"] = "성공",
            ["Auto-reposition is active (Hidden Setting). Frames are already managed automatically."] = "자동 위치 조정이 활성화되어 있습니다(숨김 설정). 프레임은 이미 자동으로 관리됩니다.",
            ["Reset"] = "초기화",
            ["Reset Styles"] = "스타일 초기화",
            ["Reset all visual customizations?"] = "모든 시각 설정을 초기화할까요?",
            ["Clear All Data"] = "모든 데이터 삭제",

            ["Profile Management"] = "프로필 관리",
            ["Manage Profiles"] = "프로필 관리",
            ["Manage Automation"] = "자동 전환 관리",
            ["Profile Switching"] = "프로필 전환",
            ["Enable Profile Switching Hotkeys"] = "프로필 전환 단축키 사용",
            ["Direct Profile [0-9]"] = "프로필 바로 전환 [0-9]",
            ["Previous Profile"] = "이전 프로필",
            ["Next Profile"] = "다음 프로필",
            ["Utilities"] = "유틸리티",
            ["Enable Focus Frame Hotkey"] = "프레임 포커스 단축키 사용",
            ["Focus Frame"] = "프레임 포커스",
            ["Enable Spot Search Hotkey"] = "Spot Search 단축키 사용",
            ["Spot Search"] = "Spot Search",
            ["Note: Changes to Global Hotkeys require an application restart to take effect."] = "참고: 전역 단축키 변경 사항은 앱을 다시 시작해야 적용됩니다.",

            ["Smart Desktop (Auto-Organize)"] = "스마트 데스크톱(자동 정리)",
            ["Enable Auto-Organize"] = "자동 정리 사용",
            ["Show execution toast notifications"] = "실행 토스트 알림 표시",
            ["Total number of rules: {0}"] = "전체 규칙 수: {0}",
            ["Enabled: {0}"] = "사용 중: {0}",
            ["Smart Desktop Rules..."] = "스마트 데스크톱 규칙...",
            ["Organize Now (Run)"] = "지금 정리(실행)",
            ["This will move existing files on your desktop to your target folders based on your rules.\n\nProceed?"] = "규칙에 따라 데스크톱의 기존 파일을 대상 폴더로 이동합니다.\n\n계속할까요?",
            ["Sweep Desktop"] = "데스크톱 정리",
            ["Note: Auto-Organize continuously monitors your Desktop for new files. When a file matches an enabled rule's conditions, it is automatically and physically moved to your target Portal Frame or Folder. Use this to keep your Desktop permanently clean and automatically route downloads to their proper locations."] = "참고: 자동 정리는 데스크톱의 새 파일을 계속 감시합니다. 파일이 사용 중인 규칙 조건과 일치하면 대상 포털 프레임이나 폴더로 자동 이동됩니다. 데스크톱을 깔끔하게 유지하고 다운로드 파일을 알맞은 위치로 보내는 데 사용할 수 있습니다.",
            ["Log"] = "로그",
            ["Enable logging"] = "로그 사용",
            ["Open Log"] = "로그 열기",
            ["Log configuration"] = "로그 설정",
            ["Log Categories"] = "로그 범주",
            ["Minimum Log Level"] = "최소 로그 수준",

            ["Smart Desktop Rules"] = "스마트 데스크톱 규칙",
            ["+ Add Rule"] = "+ 규칙 추가",
            ["− Remove"] = "− 제거",
            ["Enable this rule"] = "이 규칙 사용",
            ["Rule Name:"] = "규칙 이름:",
            ["If File Extension Is:"] = "파일 확장자가 다음이면:",
            ["Custom Extensions (e.g., *.zip; *.rar):"] = "사용자 지정 확장자(예: *.zip; *.rar):",
            ["And Filename Contains (Optional, leave blank for any):"] = "파일 이름 포함(선택, 전체는 비워두기):",
            ["Move To:"] = "이동 위치:",
            ["Generate new Portal Frame for this folder"] = "이 폴더에 새 포털 프레임 생성",
            ["If File Already Exists:"] = "파일이 이미 있으면:",
            ["Auto-Rename (e.g., File (1).jpg)"] = "자동 이름 변경(예: File (1).jpg)",
            ["Overwrite (Send old file to Recycle Bin)"] = "덮어쓰기(기존 파일은 휴지통으로 이동)",
            ["Skip (Leave on Desktop)"] = "건너뛰기(데스크톱에 남김)",
            ["Close"] = "닫기",
            ["Save Rules"] = "규칙 저장",
            ["Portal frame: {0}"] = "포털 프레임: {0}",
            ["Browse for Folder..."] = "폴더 찾아보기...",
            ["New Rule"] = "새 규칙",
            ["Last successful run: {0}"] = "마지막 성공 실행: {0}",
            ["Last successful run: Never"] = "마지막 성공 실행: 없음",
            ["Custom path: {0}"] = "사용자 지정 경로: {0}",
            ["Your rules have been saved and applied successfully."] = "규칙이 저장되고 적용되었습니다.",
            ["Saved"] = "저장됨",

            ["Focus active frames:"] = "활성 프레임 포커스:",
            ["Search active frames:"] = "활성 프레임 검색:",
            ["Cancel"] = "취소",
            ["Save"] = "저장",
            ["Language setting saved. Restart Desktop Frames to apply it everywhere."] = "언어 설정이 저장되었습니다. 모든 화면에 적용하려면 Desktop Frames를 다시 시작하세요.",
            ["Restart Required"] = "다시 시작 필요",
            ["Unnamed Frame"] = "이름 없는 프레임",
            ["Information"] = "정보",
            ["No"] = "아니요",
            ["Yes"] = "예",
            ["OK"] = "확인",
            ["Warning"] = "경고",
            ["Error"] = "오류",
            ["Critical Error"] = "치명적 오류",
            ["Profile: {0}"] = "프로필: {0}",
            ["Draw a box to create a Frame (Esc to cancel)"] = "드래그해서 프레임을 만드세요(Esc로 취소)",

            ["Enable Tabs On This Frame"] = "이 프레임에 탭 사용",
            ["Delete this Frame"] = "이 프레임 삭제",
            ["Delete frame"] = "프레임 삭제",
            ["Are you sure you want to delete this frame?"] = "이 프레임을 삭제할까요?",
            ["Export this Frame"] = "이 프레임 내보내기",
            ["Import a Frame..."] = "프레임 가져오기...",
            ["Restore Last Deleted Frame"] = "마지막 삭제 프레임 복원",
            ["Delete this frame"] = "이 프레임 삭제",
            ["Auto roll"] = "자동 말기",
            ["Always on top"] = "항상 위에 표시",
            ["Show on Show Desktop"] = "바탕화면 보기에서도 표시",
            ["Hide Frame"] = "프레임 숨기기",
            ["Peek Behind"] = "뒤쪽 잠깐 보기",
            ["Clear Dead Shortcuts"] = "깨진 바로가기 정리",
            ["Open frame folder"] = "프레임 폴더 열기",
            ["Paste Item"] = "항목 붙여넣기",
            ["Customize..."] = "사용자 지정...",
            ["Export all icons to desktop"] = "모든 아이콘을 바탕화면으로 내보내기",
            ["Add spacer"] = "여백 추가",
            ["Blank"] = "빈칸",
            ["Dot"] = "점",
            ["Name Frame After Target Path"] = "대상 경로로 프레임 이름 지정",
            ["Edit..."] = "편집...",
            ["Move..."] = "이동...",
            ["Remove"] = "제거",
            ["Copy Item"] = "항목 복사",
            ["Cut Item"] = "항목 잘라내기",
            ["Rename item"] = "항목 이름 바꾸기",
            ["Delete item"] = "항목 삭제",
            ["Run as administrator"] = "관리자 권한으로 실행",
            ["Always run as administrator"] = "항상 관리자 권한으로 실행",
            ["Copy path"] = "경로 복사",
            ["Folder path"] = "폴더 경로",
            ["Full path"] = "전체 경로",
            ["Open target folder..."] = "대상 폴더 열기...",
            ["Send to Desktop"] = "바탕화면으로 보내기",
            ["Run as different user..."] = "다른 사용자로 실행...",
            ["Always run as different user"] = "항상 다른 사용자로 실행",
            ["Add New Tab"] = "새 탭 추가",
            ["Rename Tab"] = "탭 이름 바꾸기",
            ["Delete Tab"] = "탭 삭제",
            ["item"] = "항목",
            ["items"] = "항목",
            ["Are you sure you want to delete tab\n '{0}'?\nThis tab contains {1} {2} that will be permanently removed."] = "탭 '{0}'을 삭제할까요?\n이 탭에 있는 {1}개 {2}이 영구적으로 제거됩니다.",
            ["Move Left"] = "왼쪽으로 이동",
            ["Move Right"] = "오른쪽으로 이동",
            ["Add new tab (Ctrl+Click to Import)"] = "새 탭 추가(Ctrl+클릭으로 가져오기)",
            ["Go Up"] = "위로 이동",
            ["Set current view as the new Home for this frame"] = "현재 위치를 이 프레임의 홈으로 설정",
            ["Filter files (e.g. '*.jpg' or '>*.tmp' to exclude)"] = "파일 필터(예: '*.jpg', 제외는 '>*.tmp')",
            ["Clear filter and close"] = "필터 지우고 닫기",
            ["Text Format..."] = "텍스트 서식...",
            ["Copy All Text"] = "모든 텍스트 복사",
            ["Clear All Text"] = "모든 텍스트 지우기",
            ["Word Wrap"] = "자동 줄바꿈",
            ["Spell Check"] = "맞춤법 검사",
            ["Click to finish editing"] = "클릭해서 편집 완료",
            ["Click to edit note content"] = "클릭해서 노트 내용 편집",
            ["WELCOME TO DESKTOP FRAMES +"] = "DESKTOP FRAMES +에 오신 것을 환영합니다",
            ["Roll Up/Down: Double-click the frame title bar."] = "말기/펼치기: 프레임 제목 표시줄을 더블클릭하세요.",
            ["Rename: Click the frame name, then press Enter to save."] = "이름 변경: 프레임 이름을 클릭하고 Enter로 저장하세요.",
            ["Search (SpotSearch): Press Ctrl + ` (Tilde) to find any icon instantly."] = "검색(SpotSearch): Ctrl + ` 키로 아이콘을 빠르게 찾을 수 있습니다.",
            ["Options: Click the menu icon in the top-left."] = "옵션: 좌측 상단 메뉴 아이콘을 클릭하세요.",
            ["Delete a frame: Click the × button in the top-left or use the frame menu."] = "프레임 삭제: 좌측 상단 × 버튼을 누르거나 프레임 메뉴를 사용하세요.",
            ["Reorder Icons on a frame: Ctrl + Drag icon to new position."] = "아이콘 순서 변경: Ctrl을 누른 채 아이콘을 드래그하세요.",
            ["Context Menu: Right-click icons or Frames for more options."] = "컨텍스트 메뉴: 아이콘이나 프레임을 우클릭하면 더 많은 옵션이 나옵니다.",
            ["TIP: Ctrl + Click or Ctrl + Right-click gives even more options."] = "팁: Ctrl+클릭 또는 Ctrl+우클릭을 하면 추가 옵션이 나옵니다.",
            ["Try customizing this frame! Right-click the title bar -> Customize..."] = "이 프레임을 사용자 지정해 보세요. 제목 표시줄 우클릭 -> 사용자 지정..."
        };

        public static string T(string text)
        {
            if (!IsKorean) return text;
            return Korean.TryGetValue(text, out string translated) ? translated : text;
        }

        public static string T(string format, params object[] args)
        {
            return string.Format(CultureInfo.CurrentCulture, T(format), args);
        }

        private static bool IsKorean =>
            SettingsManager.Language == "Korean" ||
            (SettingsManager.Language == "Auto" &&
                (CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ko" ||
                 CultureInfo.CurrentCulture.TwoLetterISOLanguageName == "ko"));
    }
}
